## Step 1 Concatenate all the supercontigs into a single file. Given a directory generated by HybPiper called prefix.
## This script is modified from Mossmatters github: https://github.com/mossmatters/phyloscripts/tree/master/alleles_workflow
## make sure namelist.txt is separated by \n
echo "This script is used for concatenate all the supercontigs into a single file.
All supercontigs are stored in two new files named supercontig and exon.
"

echo "Please type in the following arguments in order: 
1. The direcotory HybPiper.
2. full name of namelist.
example ./Step1.sh ./HybPiper-master/[Hybpiper_result_file]/ /[full_path]/namelist.txt
"

echo "CHECKING................................"
echo "The direcotory containing the results from HybPiper: $1."
echo "The namelist is $2"

rm -rf $1/supercontig $1/exon
mkdir $1/supercontig $1/exon

while read prefix
do

cat $1/${prefix}/*/${prefix}/sequences/intron/*_supercontig.fasta > $1/supercontig/${prefix}.supercontigs.fasta
cat $1/${prefix}/*/${prefix}/sequences/FNA/*.FNA > $1/exon/${prefix}.FNA.fasta
#cat $1/${prefix}/*/${prefix}/intronerate.gff > $1/exon/${prefix}.intronerate.fasta

done < $2


